### ISSUE TITLE
Do you plan on finishing this? 

### ISSUE THREAD

**Issue by zcuric** [alesmenzel/churchill#1]
Winston is basically [dead](https://github.com/winstonjs/winston/releases). 

We need new logger on the market! 

😄

**Comment by alesmenzel** [comment]
haha, havent got time, send some PRs

**Comment by zcuric** [comment]
https://github.com/pinojs/pino should satisfy until you are done 😸 Closing this!

**Comment by alesmenzel** [comment]
Just released a beta version, still need to finish some tests that are somewhat complicated with jest, but should be usable :v: . Also could use some polish 💎on the readme + some cool logo 😄

**Comment by zcuric** [comment]
@alesmenzel Very nice!

Any reason why Pino wasn't good fit in our `[sb](https://www.socialbakers.com/)` projects?

**Comment by alesmenzel** [comment]
I think it was for legacy reasons, we were using an old version of Winston and never actually considered pino.

**Comment by alesmenzel** [comment]
@zcuricz What are the features of pino that you cannot live with?

**Comment by zcuric** [comment]
@alesmenzel I just started using `pino`, so I can't answer yet. But what bothers me is the lack of quality pretty prints in every logger.  For that reason I'm buidling: https://github.com/zcuric/sql-log-prettifier
